### ISSUE TITLE
Develop template to encourage contribution, look nicer

### ISSUE THREAD

**Issue by billyc** [tfresource/website#11]
- VuePress 1.x broke the template I was using, need to fix hero image
- Template needs more color, better/more approachable design

**Comment by gregmacfarlane** [comment]
Is this in fact an issue for the website template or for new pages?

**Comment by billyc** [comment]
@gregmacfarlane  Oh THIS issue! Now I get it. 

I originally wrote this issue to remind me to make the page layout and appearance nice compared to the old site, which I loathed. I think that work is more or less complete.

What you're talking about now is a "New Page" template -- which I agree would also be a nice thing to have. I think Github has a site API in beta now that lets you do things like this but I will need to look into its capabilities. Happy to explore a bit.

**Comment by billyc** [comment]
Short answer is YES -- we could make a "New Page" template, by being clever with a URL passed to Github. 

for example - 

https://github.com/tfresource/website/new/source/topics?filename=mynewfile.md&value=---%0atitle:%20My%20New%20Page%0atags:blabla%0a---%0a%23%20My%20New%20Page

Right now making a new page is a hassle, so I will definitely add something like this. I'll start with a blank template that just has title and category tags.; then you & the committee can let me know what else you'd like in the template.
