### ISSUE TITLE
Describe the purpose of the subcommittee

### ISSUE THREAD

**Issue by gregmacfarlane** [tfresource/website#256]
The TRB subcommittee proposal form has a box for the following:

> Purpose of Subcommittee: Briefly describe the subcommittee goal(s) and objective(s), topics to be addressed and task(s) to be completed.

At our may meeting @moeckel and @lmz volunteered to craft a draft scope that we could agree on at our June meeting. That did not happen yesterday, but I am hoping that we can get this done before our next meeting in July. 

Can @moeckel and @lmz reply to this issue with a draft scope? We can then take comments through this issue for the next week.

**Comment by moeckel** [comment]
Yes, thanks for the reminder. We are on it.

**Comment by gregmacfarlane** [comment]
See (and comment on) the document [here](https://docs.google.com/document/d/1vsqwK8byhxFkgjnJeiZ83jY1i2w5PLHBYYMiwzzA33k/edit?usp=sharing).

**Comment by gregmacfarlane** [comment]
The subcommittee proposal was accepted by TRB, so we're good to go.
