### ISSUE TITLE
Search broken?

### ISSUE THREAD

**Issue by VinceBernardin** [tfresource/website#269]
I was just going to use the site for something and it appears that the search functionality isn't working.  Nothing happens.  Same on both my desktop in Firefox and phone in Chrome.  I'm pretty sure it was working a day or two ago, so probably was broken recently.  (I hope not by anything I did!)

**Comment by gregmacfarlane** [comment]
At this point it appears to be working (desktop Mac, chrome and Safari). I'll close unless others can verify.
