### ISSUE TITLE
Fix Style Guide acronym example

### ISSUE THREAD

**Issue by strattonma** [tfresource/website#289]
The acronym example in the Style Guide does not render correctly when the website is published.  The error happens with Chrome and Edge browsers.  It renders correctly when built locally.  @gregmacfarlane, @billyc 

https://tfresource.org/topics/Style_Guide.html

**Comment by gregmacfarlane** [comment]
So, the problem appears to be that `==TRB==` will first run the acronym generator, and then will put that in a `<pre>` literal environment. Maybe breaking this up will fix something.

**Comment by billyc** [comment]
fixed.
