### ISSUE TITLE
Best Practices for Maintaining and Archiving Models and Their Results

### ISSUE THREAD

**Issue by ClarissaLiv** [tfresource/website#295]
Idea for a topic for the website, based upon recommendations from studies like https://trid.trb.org/view/1666902 and https://www.aramis.admin.ch/Grunddaten/?ProjectID=37160.

**Comment by ClarissaLiv** [comment]
@gregmacfarlane

**Comment by gregmacfarlane** [comment]
Discussion at June Meeting:

  - some agencies are using VCS, most aren't
  - show best practices including ad-hoc methods, but talk about the benefits of VCS
  - how to use large files  (LFS)
  - Inputs, code, and runs all probably have unique concerns
  - Example/horror stories

**Comment by gregmacfarlane** [comment]
@bricegnichols is gonna write a framework (I volunteered him), and then @lmz is going to flesh it out.

**Comment by bricegnichols** [comment]
I have a draft of this that I need to push.

**Comment by bricegnichols** [comment]
https://github.com/tfresource/website/pull/381
