### ISSUE TITLE
Update of github homepage readme file

### ISSUE THREAD

**Issue by bettinardi** [tfresource/website#296]
https://github.com/tfresource/website/blob/source/README.md

The readme text should get a brief review and update.  Two specific items:
  - The hyperlink returns a 404
  - and it does not reference/link to the the TR Resource page

These are two areas that could be updated, a review and refresh might lead to a couple other updates as well.

**Comment by gregmacfarlane** [comment]
This might not be exactly what you think. If I understand correctly, the README page directly populates a portion of our homepage. That's why there's a big yaml header up top. 

Am I wrong about this @billyc?

**Comment by bettinardi** [comment]
To be clear - I'm talking about this link:
In the final report, **Metropolitan Travel Forecasting: Current Practice and Future Direction**,

**Comment by gregmacfarlane** [comment]
That's a relative link that works from the homepage at tfresource.org. Is there some way to have a more useful readme on the repo that makes this clear?

**Comment by bettinardi** [comment]
I'm confused, but it feels like I might be missing something critical.  But this is the link embedded in the readme - it doesn't look like a relative link...

https://github.com/tfresource/website/blob/source/topics/SR_288_Metropolitan_Travel_Forecasting_Current_Practice_and_Future_Direction

**Comment by billyc** [comment]
I'm not surprised you were confused, @bettinardi . The README was being used as the front page content for the actual website AND the readme text for the Github repository.

I've split it up -- now:

-  the `README.md` file is the regular README that people going to the Github repo will see on the main page
- `index.md` is the front-page content at https://tfresource.org

Hopefully this will eliminate confusion in the future.

@gregmacfarlane  - The new README is just a placeholder, let me know what you want to put there, or feel free to modify it yourself!

**Comment by billyc** [comment]
Updated the README to be a combo of the "About" and "Contributing" pages. Marking this as closed; anyone, please feel free to edit the README as you see fit.
