### ISSUE TITLE
Design_principles_of_land_use_models.md - broken links

### ISSUE THREAD

**Issue by strattonma** [tfresource/website#324]
https://tfresource.org/topics/Design_principles_of_land_use_models.html has several links to a page called "Markov_Models" which does not exist.  Either link to an external resource or create new page for Markov models.

**Comment by gregmacfarlane** [comment]
Let's try to link to wikipedia to start with.

**Comment by gregmacfarlane** [comment]
@rickdonnelly also proposed a Markov page with links to papers.

**Comment by strattonma** [comment]
@gregmacfarlane I just realized that I raised this issue after reviewing a stale version of this page in my local repository.  The live version of Design_principles_of_land_use_models.md does not have broken links.  Still, I think a Markov page makes sense.  Do you agree?

**Comment by moeckel** [comment]
Agreed, a page on Markov models would be very useful.

**Comment by gregmacfarlane** [comment]
@strattonma is going to look around for something like Wikipedia, etc.

**Comment by strattonma** [comment]
Parking possible links here:
https://setosa.io/ev/markov-chains/
https://en.wikipedia.org/wiki/Markov_chain
