### ISSUE TITLE
Add GA / cookies banner

### ISSUE THREAD

**Issue by gregmacfarlane** [tfresource/website#336]
Over the winter we talked about making the site GDPR-compliant by adding a cookies banner. Can we do this so we can keep collecting google analytics data on the up and up?

**Comment by billyc** [comment]
This is completed. There was a problem with the version I had worked on in May which prevented me from pushing it... and then I got sidetracked with other projects. We are now GDPR-compliant. No analytics are collected until after the user consents to the tracking cookie.

@gregmacfarlane  I'm curious how much this affects our analytics numbers... I imagine they will drop a bit.

**Comment by gregmacfarlane** [comment]
Thanks, billy!
