### ISSUE TITLE
🛠️ Chore: Use Github Actions to Lint Code

### ISSUE THREAD

**Issue by e-lo** [tfresource/website#367]
## Detailed Description

Markdown errors are common - we should have a way for people to make sure their formatting is correct on a push before a full-build on a pull-request.  Errors should be highlighted to the "pusher" so they are easily addressed.

## Possible Implementation

Github action on push to repository.

## Issue Ready Checklist

- [ ] Sufficiently defined

**Comment by gregmacfarlane** [comment]
This isn't a bad idea, but I think it introduces potential barriers for new contributors who might not be familiar with GitHub or code linting

**Comment by e-lo** [comment]
If the github action is doing it, the user doesn't need to 'care'
