### ISSUE TITLE
🛠️ Chore: make teams and membership public

### ISSUE THREAD

**Issue by e-lo** [tfresource/website#368]
As a contributor, I'd like to understand who has what type of access to the repositories.  

## Right now
none of the members and their privileges are public. 

![image](https://user-images.githubusercontent.com/794787/142482282-a6840228-cffa-4190-9d85-d2f9802fadf3.png)

## Desired change
change Github settings so that all teams, their privileges, and their membership public

**Comment by gregmacfarlane** [comment]
I think this is now done, once people accept the invitation.
