### ISSUE TITLE
🛠️ Chore: allow content-only changes to be merged w/ passing tests and a review from a committee member

### ISSUE THREAD

**Issue by e-lo** [tfresource/website#370]
As a contributor, I don't want to have to wait for a (unknown as of now) person to review and merge my updates if they pass tests and are deemed reasonable. 

As a current approver, I don't want to have to review and approve all minor changes.

## The way it is

A (hidden, see #368 ) list of approvers can assign reviewers and merge pull requests.

## The way it should be

Committee members should be able to merge changes if they pass tests and are approved by a committee member that isn't the author (builds on #369 )

**Comment by gregmacfarlane** [comment]
We don't have build tests per se, but more members can now merge pull requests and make assignments. (See #369 )
